#!/bin/bash
for line in `cat testbed_nodes`
do
	ssh $line 'hostname; sudo ldconfig; cd ~/blackadder/trunk/libpla; sudo ./runme.sh; sudo ldconfig; cd ../src; autoconf; ./configure --enable-pla; make; sudo make install'
done
wait
