/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_pursuit_client_nonblock_BlackadderNonBlockWrapper */

#ifndef _Included_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
#define _Included_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    create_new_ba
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_create_1new_1ba
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    close_and_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_close_1and_1delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_publish_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1publish_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_publish_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1publish_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_unpublish_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1unpublish_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_unpublish_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1unpublish_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_subscribe_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1subscribe_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_subscribe_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1subscribe_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_unsubscribe_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1unsubscribe_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_unsubscribe_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1unsubscribe_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_publish_data
 * Signature: (J[BB[B[BI)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1publish_1data
  (JNIEnv *, jobject, jlong, jbyteArray, jbyte, jbyteArray, jbyteArray, jint);
  
/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_publish_data_direct
 * Signature: (J[BB[BLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1publish_1data_1direct
  (JNIEnv *, jobject, jlong, jbyteArray, jbyte, jbyteArray, jobject, jint);

/*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    c_delete_event
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_c_1delete_1event
  (JNIEnv *, jobject, jlong);
  
  /*
 * Class:     eu_pursuit_client_nonblock_BlackadderNonBlockWrapper
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_nonblock_BlackadderNonBlockWrapper_end
  (JNIEnv *, jobject, jlong);

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void *reserved);

#ifdef __cplusplus
}
#endif
#endif
