all:
	$(CXX) $(CXXFLAGS) topology_manager.cpp tm_graph.cpp -o topology-manager $(LDFLAGS) -lblackadder -lpthread -lboost_program_options -lboost_graph -lboost_filesystem -lboost_system

clean:
	rm -f tm
